# This code creates a tool-calling workflow where an LLM can decide
# which Python functions it needs to answer the user's question.
#
# It loads the API configuration, creates the Gemini model, and
# provides it with two tools: get_stock_price and multiply.
#
# When the user asks to check TSLA's stock price and multiply it by 10,
# the LLM analyzes the request and generates a tool call.
#
# The Python program receives the tool request, finds the correct
# Python function using tool_map, executes it locally, and sends
# the result back to the LLM using a ToolMessage.
#
# The while loop is important because the LLM may need multiple
# tools in multiple rounds. For example:
#
#     get_stock_price("TSLA")
#              ↓
#     multiply(price, 10)
#
# The loop continues until the LLM no longer requests any tools.
# At that point, the LLM's response is treated as the final answer.

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, ToolMessage
from mytools import multiply, get_stock_price

# Load API keys and other variables from .env
load_dotenv()

# --------------------------------------------------
# 1. SETUP MODEL & TOOLS
# --------------------------------------------------

# Tools available to the LLM
tools = [multiply, get_stock_price]

# Map tool names to the actual Python functions
# Example: {"multiply": multiply, "get_stock_price": get_stock_price}
tool_map = {tool.name: tool for tool in tools}

# Create the Gemini model
llm = ChatGoogleGenerativeAI(
    model="gemini-3.7-flash",
    temperature=0
)
# Alternative OpenAI model:
# llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
# Give the LLM access to our tools.
# bind_tools() does NOT execute the tools.
llm_with_tools = llm.bind_tools(tools)

# --------------------------------------------------
# 2. USER QUERY
# --------------------------------------------------

query = "Can you check the stock price of TSLA and multiply that price by 10?"
# Conversation history
messages = [
    HumanMessage(content=query)
]
# --------------------------------------------------
# 3. TOOL-CALLING LOOP
# --------------------------------------------------
while True:

    # Ask the LLM what to do next
    ai_msg = llm_with_tools.invoke(messages)
    # Save the LLM response
    messages.append(ai_msg)
    # If the LLM doesn't request a tool,
    # it means we have the final answer.
    if not ai_msg.tool_calls:

        print("\n--- Final LLM Answer ---")
        print(ai_msg.content)

        # Stop the loop
        break
    # --------------------------------------------------
    # 4. EXECUTE REQUESTED TOOLS
    # --------------------------------------------------

    print(
        f"\nLLM requested "
        f"{len(ai_msg.tool_calls)} tool call(s):"
    )

    for tool_call in ai_msg.tool_calls:

        # Tool name requested by the LLM
        tool_name = tool_call["name"]

        # Arguments generated by the LLM
        tool_args = tool_call["args"]

        # Unique ID connecting the request to its result
        tool_id = tool_call["id"]

        print(
            f" -> Executing '{tool_name}' "
            f"with {tool_args}"
        )
        # Find the actual Python tool
        selected_tool = tool_map[tool_name]
        
        # Execute the Python function
        tool_output = selected_tool.invoke(tool_args)

        print(f" -> Tool result: {tool_output}")


        # Convert the tool result into a ToolMessage
        # so the LLM can understand the result.
        tool_message = ToolMessage(
            content=str(tool_output),
            tool_call_id=tool_id
        )


        # Add the result to the conversation
        messages.append(tool_message)